#!/usr/bin/env python
"""Prior parameter sampling
"""
from __future__ import print_function, division

from simtools.parsetools import Job
from simtools.job.sample import product_main, sample_main
from simtools.job.resample import resample_main, neff_main

def main(argv=None):

    job = Job()
    #job.add_command("config", show_config_main)
    job.add_command("product", product_main, 
                    help='generate ensemble from all parameter combinations')
    job.add_command("sample", sample_main, 
                    help='generate ensemble by sampling prior distributions')
    job.add_command("resample", resample_main, 
                    help='resample parameters from previous simulation')
    job.add_command("neff", neff_main, 
                    help='(resample helper) calculate effective ensemble size')
    #job.add_command("neff", neff_main)
    #job.add_command("neff", Neff)

    job.main(argv)


if __name__ == "__main__":
    main()
